# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceaf190495a686839773c9e6ab2a828dd67c0d375f2d8ffc567127e2fcc44ac5b2b5b14a3ead33bbded57227d50c991395b2d165a35b99e486c7fa3bb4b35101

test:
  secret_key_base: 0a3b7d063a7bc50eea3038d6c85d68b4dbe7139e5a558398a499939e047b0172dfc4564996d7f46e1249bec40f7071c5e647d7ae38798a3d0068c2f453bea4e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
